server:
  port: 8080
# JDBC ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${URL}
    username: ${NAME}
    password: ${PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    open-in-view: false

